```yaml
# Trading Configuration
trading:
  symbol: "SPY"
  lookback_days: 365
  risk_free_rate: 0.05
  
# Data Collection
data:
  source: "yfinance"
  interval: "1h"
  start_date: "2022-01-01"
  
# Model Parameters
model:
  population_size: 50
  generations: 100
  mutation_rate: 0.1
  
# Backtesting
backtest:
  initial_capital: 10000
  commission: 0.001
  slippage: 0.001